/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC165 } from "./IERC165";
export type { ISomniaEventHandler } from "./ISomniaEventHandler";
export type { ISomniaReactivityPrecompile } from "./ISomniaReactivityPrecompile";
export type { SomniaExtensions } from "./SomniaExtensions";
