/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export declare namespace ISomniaReactivityPrecompile {
  export type SubscriptionDataStruct = {
    eventTopics: [BytesLike, BytesLike, BytesLike, BytesLike];
    origin: AddressLike;
    caller: AddressLike;
    emitter: AddressLike;
    handlerContractAddress: AddressLike;
    handlerFunctionSelector: BytesLike;
    priorityFeePerGas: BigNumberish;
    maxFeePerGas: BigNumberish;
    gasLimit: BigNumberish;
    isGuaranteed: boolean;
    isCoalesced: boolean;
  };

  export type SubscriptionDataStructOutput = [
    eventTopics: [string, string, string, string],
    origin: string,
    caller: string,
    emitter: string,
    handlerContractAddress: string,
    handlerFunctionSelector: string,
    priorityFeePerGas: bigint,
    maxFeePerGas: bigint,
    gasLimit: bigint,
    isGuaranteed: boolean,
    isCoalesced: boolean
  ] & {
    eventTopics: [string, string, string, string];
    origin: string;
    caller: string;
    emitter: string;
    handlerContractAddress: string;
    handlerFunctionSelector: string;
    priorityFeePerGas: bigint;
    maxFeePerGas: bigint;
    gasLimit: bigint;
    isGuaranteed: boolean;
    isCoalesced: boolean;
  };
}

export interface ISomniaReactivityPrecompileInterface extends Interface {
  getFunction(
    nameOrSignature: "getSubscriptionInfo" | "subscribe" | "unsubscribe"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BlockTick"
      | "EpochTick"
      | "Schedule"
      | "SubscriptionCreated"
      | "SubscriptionRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getSubscriptionInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [ISomniaReactivityPrecompile.SubscriptionDataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "unsubscribe",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSubscriptionInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unsubscribe",
    data: BytesLike
  ): Result;
}

export namespace BlockTickEvent {
  export type InputTuple = [blockNumber: BigNumberish];
  export type OutputTuple = [blockNumber: bigint];
  export interface OutputObject {
    blockNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EpochTickEvent {
  export type InputTuple = [
    epochNumber: BigNumberish,
    blockNumber: BigNumberish
  ];
  export type OutputTuple = [epochNumber: bigint, blockNumber: bigint];
  export interface OutputObject {
    epochNumber: bigint;
    blockNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScheduleEvent {
  export type InputTuple = [timestampMillis: BigNumberish];
  export type OutputTuple = [timestampMillis: bigint];
  export interface OutputObject {
    timestampMillis: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCreatedEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    owner: AddressLike,
    subscriptionData: ISomniaReactivityPrecompile.SubscriptionDataStruct
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    owner: string,
    subscriptionData: ISomniaReactivityPrecompile.SubscriptionDataStructOutput
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    owner: string;
    subscriptionData: ISomniaReactivityPrecompile.SubscriptionDataStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionRemovedEvent {
  export type InputTuple = [subscriptionId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [subscriptionId: bigint, owner: string];
  export interface OutputObject {
    subscriptionId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISomniaReactivityPrecompile extends BaseContract {
  connect(runner?: ContractRunner | null): ISomniaReactivityPrecompile;
  waitForDeployment(): Promise<this>;

  interface: ISomniaReactivityPrecompileInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getSubscriptionInfo: TypedContractMethod<
    [subscriptionId: BigNumberish],
    [
      [ISomniaReactivityPrecompile.SubscriptionDataStructOutput, string] & {
        subscriptionData: ISomniaReactivityPrecompile.SubscriptionDataStructOutput;
        owner: string;
      }
    ],
    "view"
  >;

  subscribe: TypedContractMethod<
    [subscriptionData: ISomniaReactivityPrecompile.SubscriptionDataStruct],
    [bigint],
    "nonpayable"
  >;

  unsubscribe: TypedContractMethod<
    [subscriptionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getSubscriptionInfo"
  ): TypedContractMethod<
    [subscriptionId: BigNumberish],
    [
      [ISomniaReactivityPrecompile.SubscriptionDataStructOutput, string] & {
        subscriptionData: ISomniaReactivityPrecompile.SubscriptionDataStructOutput;
        owner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<
    [subscriptionData: ISomniaReactivityPrecompile.SubscriptionDataStruct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unsubscribe"
  ): TypedContractMethod<[subscriptionId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BlockTick"
  ): TypedContractEvent<
    BlockTickEvent.InputTuple,
    BlockTickEvent.OutputTuple,
    BlockTickEvent.OutputObject
  >;
  getEvent(
    key: "EpochTick"
  ): TypedContractEvent<
    EpochTickEvent.InputTuple,
    EpochTickEvent.OutputTuple,
    EpochTickEvent.OutputObject
  >;
  getEvent(
    key: "Schedule"
  ): TypedContractEvent<
    ScheduleEvent.InputTuple,
    ScheduleEvent.OutputTuple,
    ScheduleEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCreated"
  ): TypedContractEvent<
    SubscriptionCreatedEvent.InputTuple,
    SubscriptionCreatedEvent.OutputTuple,
    SubscriptionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionRemoved"
  ): TypedContractEvent<
    SubscriptionRemovedEvent.InputTuple,
    SubscriptionRemovedEvent.OutputTuple,
    SubscriptionRemovedEvent.OutputObject
  >;

  filters: {
    "BlockTick(uint64)": TypedContractEvent<
      BlockTickEvent.InputTuple,
      BlockTickEvent.OutputTuple,
      BlockTickEvent.OutputObject
    >;
    BlockTick: TypedContractEvent<
      BlockTickEvent.InputTuple,
      BlockTickEvent.OutputTuple,
      BlockTickEvent.OutputObject
    >;

    "EpochTick(uint64,uint64)": TypedContractEvent<
      EpochTickEvent.InputTuple,
      EpochTickEvent.OutputTuple,
      EpochTickEvent.OutputObject
    >;
    EpochTick: TypedContractEvent<
      EpochTickEvent.InputTuple,
      EpochTickEvent.OutputTuple,
      EpochTickEvent.OutputObject
    >;

    "Schedule(uint256)": TypedContractEvent<
      ScheduleEvent.InputTuple,
      ScheduleEvent.OutputTuple,
      ScheduleEvent.OutputObject
    >;
    Schedule: TypedContractEvent<
      ScheduleEvent.InputTuple,
      ScheduleEvent.OutputTuple,
      ScheduleEvent.OutputObject
    >;

    "SubscriptionCreated(uint256,address,tuple)": TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;
    SubscriptionCreated: TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;

    "SubscriptionRemoved(uint256,address)": TypedContractEvent<
      SubscriptionRemovedEvent.InputTuple,
      SubscriptionRemovedEvent.OutputTuple,
      SubscriptionRemovedEvent.OutputObject
    >;
    SubscriptionRemoved: TypedContractEvent<
      SubscriptionRemovedEvent.InputTuple,
      SubscriptionRemovedEvent.OutputTuple,
      SubscriptionRemovedEvent.OutputObject
    >;
  };
}
