/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface SomniaExtensionsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_HANDLER_GAS_LIMIT"
      | "DEFAULT_MAX_FEE_PER_GAS"
      | "DEFAULT_PRIORITY_FEE_PER_GAS"
      | "MAXIMUM_HANDLER_GAS_LIMIT"
      | "MINIMUM_BASE_FEE_PER_GAS"
      | "SOMNIA_REACTIVITY_PRECOMPILE_ADDRESS"
      | "SUBSCRIPTION_OWNER_MINIMUM_BALANCE"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_HANDLER_GAS_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_MAX_FEE_PER_GAS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_PRIORITY_FEE_PER_GAS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAXIMUM_HANDLER_GAS_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINIMUM_BASE_FEE_PER_GAS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SOMNIA_REACTIVITY_PRECOMPILE_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUBSCRIPTION_OWNER_MINIMUM_BALANCE",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_HANDLER_GAS_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_MAX_FEE_PER_GAS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_PRIORITY_FEE_PER_GAS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAXIMUM_HANDLER_GAS_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINIMUM_BASE_FEE_PER_GAS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SOMNIA_REACTIVITY_PRECOMPILE_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUBSCRIPTION_OWNER_MINIMUM_BALANCE",
    data: BytesLike
  ): Result;
}

export interface SomniaExtensions extends BaseContract {
  connect(runner?: ContractRunner | null): SomniaExtensions;
  waitForDeployment(): Promise<this>;

  interface: SomniaExtensionsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_HANDLER_GAS_LIMIT: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_MAX_FEE_PER_GAS: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_PRIORITY_FEE_PER_GAS: TypedContractMethod<[], [bigint], "view">;

  MAXIMUM_HANDLER_GAS_LIMIT: TypedContractMethod<[], [bigint], "view">;

  MINIMUM_BASE_FEE_PER_GAS: TypedContractMethod<[], [bigint], "view">;

  SOMNIA_REACTIVITY_PRECOMPILE_ADDRESS: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  SUBSCRIPTION_OWNER_MINIMUM_BALANCE: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_HANDLER_GAS_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_MAX_FEE_PER_GAS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_PRIORITY_FEE_PER_GAS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAXIMUM_HANDLER_GAS_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MINIMUM_BASE_FEE_PER_GAS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SOMNIA_REACTIVITY_PRECOMPILE_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SUBSCRIPTION_OWNER_MINIMUM_BALANCE"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
