/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISomniaEventHandler,
  ISomniaEventHandlerInterface,
} from "../../../../../@somnia-chain/reactivity-contracts/contracts/interfaces/ISomniaEventHandler";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "emitter",
        type: "address",
      },
      {
        internalType: "bytes32[]",
        name: "eventTopics",
        type: "bytes32[]",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onEvent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISomniaEventHandler__factory {
  static readonly abi = _abi;
  static createInterface(): ISomniaEventHandlerInterface {
    return new Interface(_abi) as ISomniaEventHandlerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISomniaEventHandler {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISomniaEventHandler;
  }
}
