/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISomniaReactivityPrecompile,
  ISomniaReactivityPrecompileInterface,
} from "../../../../../@somnia-chain/reactivity-contracts/contracts/interfaces/ISomniaReactivityPrecompile";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint64",
        name: "blockNumber",
        type: "uint64",
      },
    ],
    name: "BlockTick",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint64",
        name: "epochNumber",
        type: "uint64",
      },
      {
        indexed: true,
        internalType: "uint64",
        name: "blockNumber",
        type: "uint64",
      },
    ],
    name: "EpochTick",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "timestampMillis",
        type: "uint256",
      },
    ],
    name: "Schedule",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "subscriptionId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        components: [
          {
            internalType: "bytes32[4]",
            name: "eventTopics",
            type: "bytes32[4]",
          },
          {
            internalType: "address",
            name: "origin",
            type: "address",
          },
          {
            internalType: "address",
            name: "caller",
            type: "address",
          },
          {
            internalType: "address",
            name: "emitter",
            type: "address",
          },
          {
            internalType: "address",
            name: "handlerContractAddress",
            type: "address",
          },
          {
            internalType: "bytes4",
            name: "handlerFunctionSelector",
            type: "bytes4",
          },
          {
            internalType: "uint64",
            name: "priorityFeePerGas",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "maxFeePerGas",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "gasLimit",
            type: "uint64",
          },
          {
            internalType: "bool",
            name: "isGuaranteed",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isCoalesced",
            type: "bool",
          },
        ],
        indexed: false,
        internalType: "struct ISomniaReactivityPrecompile.SubscriptionData",
        name: "subscriptionData",
        type: "tuple",
      },
    ],
    name: "SubscriptionCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "subscriptionId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "SubscriptionRemoved",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "subscriptionId",
        type: "uint256",
      },
    ],
    name: "getSubscriptionInfo",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32[4]",
            name: "eventTopics",
            type: "bytes32[4]",
          },
          {
            internalType: "address",
            name: "origin",
            type: "address",
          },
          {
            internalType: "address",
            name: "caller",
            type: "address",
          },
          {
            internalType: "address",
            name: "emitter",
            type: "address",
          },
          {
            internalType: "address",
            name: "handlerContractAddress",
            type: "address",
          },
          {
            internalType: "bytes4",
            name: "handlerFunctionSelector",
            type: "bytes4",
          },
          {
            internalType: "uint64",
            name: "priorityFeePerGas",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "maxFeePerGas",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "gasLimit",
            type: "uint64",
          },
          {
            internalType: "bool",
            name: "isGuaranteed",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isCoalesced",
            type: "bool",
          },
        ],
        internalType: "struct ISomniaReactivityPrecompile.SubscriptionData",
        name: "subscriptionData",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32[4]",
            name: "eventTopics",
            type: "bytes32[4]",
          },
          {
            internalType: "address",
            name: "origin",
            type: "address",
          },
          {
            internalType: "address",
            name: "caller",
            type: "address",
          },
          {
            internalType: "address",
            name: "emitter",
            type: "address",
          },
          {
            internalType: "address",
            name: "handlerContractAddress",
            type: "address",
          },
          {
            internalType: "bytes4",
            name: "handlerFunctionSelector",
            type: "bytes4",
          },
          {
            internalType: "uint64",
            name: "priorityFeePerGas",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "maxFeePerGas",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "gasLimit",
            type: "uint64",
          },
          {
            internalType: "bool",
            name: "isGuaranteed",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isCoalesced",
            type: "bool",
          },
        ],
        internalType: "struct ISomniaReactivityPrecompile.SubscriptionData",
        name: "subscriptionData",
        type: "tuple",
      },
    ],
    name: "subscribe",
    outputs: [
      {
        internalType: "uint256",
        name: "subscriptionId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "subscriptionId",
        type: "uint256",
      },
    ],
    name: "unsubscribe",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISomniaReactivityPrecompile__factory {
  static readonly abi = _abi;
  static createInterface(): ISomniaReactivityPrecompileInterface {
    return new Interface(_abi) as ISomniaReactivityPrecompileInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISomniaReactivityPrecompile {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISomniaReactivityPrecompile;
  }
}
