/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  SomniaExtensions,
  SomniaExtensionsInterface,
} from "../../../../../@somnia-chain/reactivity-contracts/contracts/interfaces/SomniaExtensions";

const _abi = [
  {
    inputs: [],
    name: "BlockInPast",
    type: "error",
  },
  {
    inputs: [],
    name: "EmptyFilter",
    type: "error",
  },
  {
    inputs: [],
    name: "GasLimitExceeded",
    type: "error",
  },
  {
    inputs: [],
    name: "GasLimitZero",
    type: "error",
  },
  {
    inputs: [],
    name: "HandlerZeroAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "InsufficientBalance",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidMaxFeePerGas",
    type: "error",
  },
  {
    inputs: [],
    name: "TimestampInPast",
    type: "error",
  },
  {
    inputs: [],
    name: "UnsubscribeFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "DEFAULT_HANDLER_GAS_LIMIT",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DEFAULT_MAX_FEE_PER_GAS",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DEFAULT_PRIORITY_FEE_PER_GAS",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAXIMUM_HANDLER_GAS_LIMIT",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MINIMUM_BASE_FEE_PER_GAS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SOMNIA_REACTIVITY_PRECOMPILE_ADDRESS",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SUBSCRIPTION_OWNER_MINIMUM_BALANCE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523460195761015c908161001f823930815050f35b600080fdfe608080604052600436101561001357600080fd5b60003560e01c9081631b4d89671461010d57508063712f31f7146100f55780637adc3b42146100db578063a21e3a42146100c0578063cce6fcef146100a9578063cdbaa81c146100905763ce9e11341461006c57600080fd5b600036600319011261008b5760206040516801bc16d674ec8000008152f35b600080fd5b600036600319011261008b576020604051629896808152f35b600036600319011261008b57602060405160008152f35b600036600319011261008b5760206040516404a817c8008152f35b600036600319011261008b576020604051630bebc2008152f35b600036600319011261008b5760206040516101008152f35b600036600319011261008b5780640165a0bc0060209252f3fea2646970667358221220419ddb858792b300c3b4b6745bc9454d51176caa6c89a3f37034b0b1f93928c464736f6c634300081e0033";

type SomniaExtensionsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SomniaExtensionsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SomniaExtensions__factory extends ContractFactory {
  constructor(...args: SomniaExtensionsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SomniaExtensions & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SomniaExtensions__factory {
    return super.connect(runner) as SomniaExtensions__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SomniaExtensionsInterface {
    return new Interface(_abi) as SomniaExtensionsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SomniaExtensions {
    return new Contract(address, _abi, runner) as unknown as SomniaExtensions;
  }
}
