/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export type ResponseStruct = {
  validator: AddressLike;
  result: BytesLike;
  status: BigNumberish;
  receipt: BigNumberish;
  timestamp: BigNumberish;
  executionCost: BigNumberish;
};

export type ResponseStructOutput = [
  validator: string,
  result: string,
  status: bigint,
  receipt: bigint,
  timestamp: bigint,
  executionCost: bigint
] & {
  validator: string;
  result: string;
  status: bigint;
  receipt: bigint;
  timestamp: bigint;
  executionCost: bigint;
};

export type RequestStruct = {
  id: BigNumberish;
  requester: AddressLike;
  callbackAddress: AddressLike;
  callbackSelector: BytesLike;
  subcommittee: AddressLike[];
  responses: ResponseStruct[];
  responseCount: BigNumberish;
  failureCount: BigNumberish;
  threshold: BigNumberish;
  createdAt: BigNumberish;
  deadline: BigNumberish;
  status: BigNumberish;
  consensusType: BigNumberish;
  remainingBudget: BigNumberish;
  perAgentBudget: BigNumberish;
};

export type RequestStructOutput = [
  id: bigint,
  requester: string,
  callbackAddress: string,
  callbackSelector: string,
  subcommittee: string[],
  responses: ResponseStructOutput[],
  responseCount: bigint,
  failureCount: bigint,
  threshold: bigint,
  createdAt: bigint,
  deadline: bigint,
  status: bigint,
  consensusType: bigint,
  remainingBudget: bigint,
  perAgentBudget: bigint
] & {
  id: bigint;
  requester: string;
  callbackAddress: string;
  callbackSelector: string;
  subcommittee: string[];
  responses: ResponseStructOutput[];
  responseCount: bigint;
  failureCount: bigint;
  threshold: bigint;
  createdAt: bigint;
  deadline: bigint;
  status: bigint;
  consensusType: bigint;
  remainingBudget: bigint;
  perAgentBudget: bigint;
};

export interface NegotiationGatewayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "JSON_API_AGENT_ID"
      | "JSON_FETCH_COST_PER_AGENT"
      | "SUBCOMMITTEE_SIZE"
      | "agentRegistry"
      | "cancelSubscription"
      | "executorQuoteFeedUrl"
      | "handleNegotiationResponse"
      | "initSubscription"
      | "onEvent"
      | "owner"
      | "platform"
      | "registry"
      | "renounceOwnership"
      | "setExecutorQuoteFeedUrl"
      | "supportsInterface"
      | "transferOwnership"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExecutorSelected"
      | "NegotiationFailed"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "JSON_API_AGENT_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "JSON_FETCH_COST_PER_AGENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUBCOMMITTEE_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSubscription",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executorQuoteFeedUrl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "handleNegotiationResponse",
    values: [BigNumberish, ResponseStruct[], BigNumberish, RequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "initSubscription",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onEvent",
    values: [AddressLike, BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "platform", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setExecutorQuoteFeedUrl",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "JSON_API_AGENT_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "JSON_FETCH_COST_PER_AGENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUBCOMMITTEE_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executorQuoteFeedUrl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleNegotiationResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onEvent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "platform", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExecutorQuoteFeedUrl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace ExecutorSelectedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    executor: AddressLike,
    quotedFee: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    executor: string,
    quotedFee: bigint
  ];
  export interface OutputObject {
    intentId: string;
    executor: string;
    quotedFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NegotiationFailedEvent {
  export type InputTuple = [intentId: BytesLike, reason: string];
  export type OutputTuple = [intentId: string, reason: string];
  export interface OutputObject {
    intentId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NegotiationGateway extends BaseContract {
  connect(runner?: ContractRunner | null): NegotiationGateway;
  waitForDeployment(): Promise<this>;

  interface: NegotiationGatewayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  JSON_API_AGENT_ID: TypedContractMethod<[], [bigint], "view">;

  JSON_FETCH_COST_PER_AGENT: TypedContractMethod<[], [bigint], "view">;

  SUBCOMMITTEE_SIZE: TypedContractMethod<[], [bigint], "view">;

  agentRegistry: TypedContractMethod<[], [string], "view">;

  cancelSubscription: TypedContractMethod<[], [void], "nonpayable">;

  executorQuoteFeedUrl: TypedContractMethod<[], [string], "view">;

  handleNegotiationResponse: TypedContractMethod<
    [
      requestId: BigNumberish,
      responses: ResponseStruct[],
      status: BigNumberish,
      arg3: RequestStruct
    ],
    [void],
    "nonpayable"
  >;

  initSubscription: TypedContractMethod<[], [void], "nonpayable">;

  onEvent: TypedContractMethod<
    [emitter: AddressLike, eventTopics: BytesLike[], data: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platform: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setExecutorQuoteFeedUrl: TypedContractMethod<
    [url: string],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawFunds: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "JSON_API_AGENT_ID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "JSON_FETCH_COST_PER_AGENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SUBCOMMITTEE_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelSubscription"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executorQuoteFeedUrl"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "handleNegotiationResponse"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      responses: ResponseStruct[],
      status: BigNumberish,
      arg3: RequestStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initSubscription"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "onEvent"
  ): TypedContractMethod<
    [emitter: AddressLike, eventTopics: BytesLike[], data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platform"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExecutorQuoteFeedUrl"
  ): TypedContractMethod<[url: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ExecutorSelected"
  ): TypedContractEvent<
    ExecutorSelectedEvent.InputTuple,
    ExecutorSelectedEvent.OutputTuple,
    ExecutorSelectedEvent.OutputObject
  >;
  getEvent(
    key: "NegotiationFailed"
  ): TypedContractEvent<
    NegotiationFailedEvent.InputTuple,
    NegotiationFailedEvent.OutputTuple,
    NegotiationFailedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ExecutorSelected(bytes32,address,uint256)": TypedContractEvent<
      ExecutorSelectedEvent.InputTuple,
      ExecutorSelectedEvent.OutputTuple,
      ExecutorSelectedEvent.OutputObject
    >;
    ExecutorSelected: TypedContractEvent<
      ExecutorSelectedEvent.InputTuple,
      ExecutorSelectedEvent.OutputTuple,
      ExecutorSelectedEvent.OutputObject
    >;

    "NegotiationFailed(bytes32,string)": TypedContractEvent<
      NegotiationFailedEvent.InputTuple,
      NegotiationFailedEvent.OutputTuple,
      NegotiationFailedEvent.OutputObject
    >;
    NegotiationFailed: TypedContractEvent<
      NegotiationFailedEvent.InputTuple,
      NegotiationFailedEvent.OutputTuple,
      NegotiationFailedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
