/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace PaymentLib {
  export type RecipientStruct = {
    role: string;
    wallet: AddressLike;
    bps: BigNumberish;
  };

  export type RecipientStructOutput = [
    role: string,
    wallet: string,
    bps: bigint
  ] & { role: string; wallet: string; bps: bigint };

  export type PaymentIntentStruct = {
    intentId: BytesLike;
    payer: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    recipients: PaymentLib.RecipientStruct[];
    status: BigNumberish;
    createdAt: BigNumberish;
    deadline: BigNumberish;
    context: string;
    selectedExecutor: AddressLike;
    executorFee: BigNumberish;
  };

  export type PaymentIntentStructOutput = [
    intentId: string,
    payer: string,
    token: string,
    amount: bigint,
    recipients: PaymentLib.RecipientStructOutput[],
    status: bigint,
    createdAt: bigint,
    deadline: bigint,
    context: string,
    selectedExecutor: string,
    executorFee: bigint
  ] & {
    intentId: string;
    payer: string;
    token: string;
    amount: bigint;
    recipients: PaymentLib.RecipientStructOutput[];
    status: bigint;
    createdAt: bigint;
    deadline: bigint;
    context: string;
    selectedExecutor: string;
    executorFee: bigint;
  };
}

export interface IPaymentIntentRegistryInterface extends Interface {
  getFunction(nameOrSignature: "getIntent" | "updateStatus"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getIntent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStatus",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getIntent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateStatus",
    data: BytesLike
  ): Result;
}

export interface IPaymentIntentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IPaymentIntentRegistry;
  waitForDeployment(): Promise<this>;

  interface: IPaymentIntentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getIntent: TypedContractMethod<
    [intentId: BytesLike],
    [
      [PaymentLib.PaymentIntentStructOutput, PaymentLib.RecipientStructOutput[]]
    ],
    "view"
  >;

  updateStatus: TypedContractMethod<
    [intentId: BytesLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getIntent"
  ): TypedContractMethod<
    [intentId: BytesLike],
    [
      [PaymentLib.PaymentIntentStructOutput, PaymentLib.RecipientStructOutput[]]
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateStatus"
  ): TypedContractMethod<
    [intentId: BytesLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
