/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AgentRegistry {
  export type AgentStruct = {
    wallet: AddressLike;
    role: string;
    active: boolean;
    heartbeatAt: BigNumberish;
    successCount: BigNumberish;
    failCount: BigNumberish;
  };

  export type AgentStructOutput = [
    wallet: string,
    role: string,
    active: boolean,
    heartbeatAt: bigint,
    successCount: bigint,
    failCount: bigint
  ] & {
    wallet: string;
    role: string;
    active: boolean;
    heartbeatAt: bigint;
    successCount: bigint;
    failCount: bigint;
  };
}

export interface AgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivateAgent"
      | "getActiveExecutors"
      | "getAgent"
      | "getAllAgents"
      | "isActiveAgent"
      | "owner"
      | "recordHeartbeat"
      | "recordOutcome"
      | "registerAgent"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentDeactivated"
      | "AgentRegistered"
      | "AgentStatUpdated"
      | "HeartbeatRecorded"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivateAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveExecutors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordHeartbeat",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordOutcome",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "deactivateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveExecutors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isActiveAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordHeartbeat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AgentDeactivatedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [wallet: AddressLike, role: string];
  export type OutputTuple = [wallet: string, role: string];
  export interface OutputObject {
    wallet: string;
    role: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentStatUpdatedEvent {
  export type InputTuple = [wallet: AddressLike, success: boolean];
  export type OutputTuple = [wallet: string, success: boolean];
  export interface OutputObject {
    wallet: string;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HeartbeatRecordedEvent {
  export type InputTuple = [wallet: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [wallet: string, timestamp: bigint];
  export interface OutputObject {
    wallet: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivateAgent: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  getActiveExecutors: TypedContractMethod<[], [string[]], "view">;

  getAgent: TypedContractMethod<
    [wallet: AddressLike],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;

  getAllAgents: TypedContractMethod<[], [string[]], "view">;

  isActiveAgent: TypedContractMethod<[wallet: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordHeartbeat: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  recordOutcome: TypedContractMethod<
    [wallet: AddressLike, success: boolean],
    [void],
    "nonpayable"
  >;

  registerAgent: TypedContractMethod<
    [wallet: AddressLike, role: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivateAgent"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveExecutors"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllAgents"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isActiveAgent"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordHeartbeat"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordOutcome"
  ): TypedContractMethod<
    [wallet: AddressLike, success: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [wallet: AddressLike, role: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgentDeactivated"
  ): TypedContractEvent<
    AgentDeactivatedEvent.InputTuple,
    AgentDeactivatedEvent.OutputTuple,
    AgentDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentStatUpdated"
  ): TypedContractEvent<
    AgentStatUpdatedEvent.InputTuple,
    AgentStatUpdatedEvent.OutputTuple,
    AgentStatUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "HeartbeatRecorded"
  ): TypedContractEvent<
    HeartbeatRecordedEvent.InputTuple,
    HeartbeatRecordedEvent.OutputTuple,
    HeartbeatRecordedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AgentDeactivated(address)": TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;
    AgentDeactivated: TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;

    "AgentRegistered(address,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentStatUpdated(address,bool)": TypedContractEvent<
      AgentStatUpdatedEvent.InputTuple,
      AgentStatUpdatedEvent.OutputTuple,
      AgentStatUpdatedEvent.OutputObject
    >;
    AgentStatUpdated: TypedContractEvent<
      AgentStatUpdatedEvent.InputTuple,
      AgentStatUpdatedEvent.OutputTuple,
      AgentStatUpdatedEvent.OutputObject
    >;

    "HeartbeatRecorded(address,uint256)": TypedContractEvent<
      HeartbeatRecordedEvent.InputTuple,
      HeartbeatRecordedEvent.OutputTuple,
      HeartbeatRecordedEvent.OutputObject
    >;
    HeartbeatRecorded: TypedContractEvent<
      HeartbeatRecordedEvent.InputTuple,
      HeartbeatRecordedEvent.OutputTuple,
      HeartbeatRecordedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
