/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace PaymentLib {
  export type RecipientStruct = {
    role: string;
    wallet: AddressLike;
    bps: BigNumberish;
  };

  export type RecipientStructOutput = [
    role: string,
    wallet: string,
    bps: bigint
  ] & { role: string; wallet: string; bps: bigint };

  export type PaymentIntentStruct = {
    intentId: BytesLike;
    payer: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    recipients: PaymentLib.RecipientStruct[];
    status: BigNumberish;
    createdAt: BigNumberish;
    deadline: BigNumberish;
    context: string;
  };

  export type PaymentIntentStructOutput = [
    intentId: string,
    payer: string,
    token: string,
    amount: bigint,
    recipients: PaymentLib.RecipientStructOutput[],
    status: bigint,
    createdAt: bigint,
    deadline: bigint,
    context: string
  ] & {
    intentId: string;
    payer: string;
    token: string;
    amount: bigint;
    recipients: PaymentLib.RecipientStructOutput[];
    status: bigint;
    createdAt: bigint;
    deadline: bigint;
    context: string;
  };
}

export interface PaymentIntentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedCaller"
      | "createIntent"
      | "getIntent"
      | "getStatus"
      | "owner"
      | "renounceOwnership"
      | "setAuthorizedCaller"
      | "transferOwnership"
      | "updateStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorizedCallerSet"
      | "OwnershipTransferred"
      | "PaymentIntentCreated"
      | "StatusUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedCaller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createIntent",
    values: [
      AddressLike,
      BigNumberish,
      PaymentLib.RecipientStruct[],
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedCaller",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStatus",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getIntent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStatus",
    data: BytesLike
  ): Result;
}

export namespace AuthorizedCallerSetEvent {
  export type InputTuple = [caller: AddressLike];
  export type OutputTuple = [caller: string];
  export interface OutputObject {
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentIntentCreatedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    payer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [intentId: string, payer: string, amount: bigint];
  export interface OutputObject {
    intentId: string;
    payer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatusUpdatedEvent {
  export type InputTuple = [intentId: BytesLike, newStatus: BigNumberish];
  export type OutputTuple = [intentId: string, newStatus: bigint];
  export interface OutputObject {
    intentId: string;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaymentIntentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PaymentIntentRegistry;
  waitForDeployment(): Promise<this>;

  interface: PaymentIntentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedCaller: TypedContractMethod<[], [string], "view">;

  createIntent: TypedContractMethod<
    [
      token: AddressLike,
      amount: BigNumberish,
      recipients: PaymentLib.RecipientStruct[],
      deadline: BigNumberish,
      context: string
    ],
    [string],
    "nonpayable"
  >;

  getIntent: TypedContractMethod<
    [intentId: BytesLike],
    [
      [
        PaymentLib.PaymentIntentStructOutput,
        PaymentLib.RecipientStructOutput[]
      ] & {
        intent: PaymentLib.PaymentIntentStructOutput;
        recipients: PaymentLib.RecipientStructOutput[];
      }
    ],
    "view"
  >;

  getStatus: TypedContractMethod<[intentId: BytesLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAuthorizedCaller: TypedContractMethod<
    [_caller: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateStatus: TypedContractMethod<
    [intentId: BytesLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedCaller"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createIntent"
  ): TypedContractMethod<
    [
      token: AddressLike,
      amount: BigNumberish,
      recipients: PaymentLib.RecipientStruct[],
      deadline: BigNumberish,
      context: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getIntent"
  ): TypedContractMethod<
    [intentId: BytesLike],
    [
      [
        PaymentLib.PaymentIntentStructOutput,
        PaymentLib.RecipientStructOutput[]
      ] & {
        intent: PaymentLib.PaymentIntentStructOutput;
        recipients: PaymentLib.RecipientStructOutput[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStatus"
  ): TypedContractMethod<[intentId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuthorizedCaller"
  ): TypedContractMethod<[_caller: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateStatus"
  ): TypedContractMethod<
    [intentId: BytesLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AuthorizedCallerSet"
  ): TypedContractEvent<
    AuthorizedCallerSetEvent.InputTuple,
    AuthorizedCallerSetEvent.OutputTuple,
    AuthorizedCallerSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentIntentCreated"
  ): TypedContractEvent<
    PaymentIntentCreatedEvent.InputTuple,
    PaymentIntentCreatedEvent.OutputTuple,
    PaymentIntentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "StatusUpdated"
  ): TypedContractEvent<
    StatusUpdatedEvent.InputTuple,
    StatusUpdatedEvent.OutputTuple,
    StatusUpdatedEvent.OutputObject
  >;

  filters: {
    "AuthorizedCallerSet(address)": TypedContractEvent<
      AuthorizedCallerSetEvent.InputTuple,
      AuthorizedCallerSetEvent.OutputTuple,
      AuthorizedCallerSetEvent.OutputObject
    >;
    AuthorizedCallerSet: TypedContractEvent<
      AuthorizedCallerSetEvent.InputTuple,
      AuthorizedCallerSetEvent.OutputTuple,
      AuthorizedCallerSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentIntentCreated(bytes32,address,uint256)": TypedContractEvent<
      PaymentIntentCreatedEvent.InputTuple,
      PaymentIntentCreatedEvent.OutputTuple,
      PaymentIntentCreatedEvent.OutputObject
    >;
    PaymentIntentCreated: TypedContractEvent<
      PaymentIntentCreatedEvent.InputTuple,
      PaymentIntentCreatedEvent.OutputTuple,
      PaymentIntentCreatedEvent.OutputObject
    >;

    "StatusUpdated(bytes32,uint8)": TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;
    StatusUpdated: TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;
  };
}
