/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  PaymentLib,
  PaymentLibInterface,
} from "../../../contracts/libraries/PaymentLib";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "total",
        type: "uint256",
      },
    ],
    name: "BpsMismatch",
    type: "error",
  },
  {
    inputs: [],
    name: "BPS_DENOMINATOR",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346018576076908161001e823930815050f35b600080fdfe6080806040526004361015601257600080fd5b60003560e01c63e1a4521814602657600080fd5b6000366003190112603b578061271060209252f35b600080fdfea264697066735822122054639cf8a0f3a3263e3a189aedfa02301436bdf0084e53081610e694afe3148a64736f6c63430008180033";

type PaymentLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PaymentLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PaymentLib__factory extends ContractFactory {
  constructor(...args: PaymentLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PaymentLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PaymentLib__factory {
    return super.connect(runner) as PaymentLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PaymentLibInterface {
    return new Interface(_abi) as PaymentLibInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): PaymentLib {
    return new Contract(address, _abi, runner) as unknown as PaymentLib;
  }
}
