/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IJsonApiAgent,
  IJsonApiAgentInterface,
} from "../../../../contracts/core/NegotiationGateway.sol/IJsonApiAgent";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "url",
        type: "string",
      },
      {
        internalType: "string",
        name: "selector",
        type: "string",
      },
      {
        internalType: "uint8",
        name: "decimals",
        type: "uint8",
      },
    ],
    name: "fetchUint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IJsonApiAgent__factory {
  static readonly abi = _abi;
  static createInterface(): IJsonApiAgentInterface {
    return new Interface(_abi) as IJsonApiAgentInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IJsonApiAgent {
    return new Contract(address, _abi, runner) as unknown as IJsonApiAgent;
  }
}
