/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPaymentIntentRegistry,
  IPaymentIntentRegistryInterface,
} from "../../../../contracts/core/NegotiationGateway.sol/IPaymentIntentRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "intentId",
        type: "bytes32",
      },
    ],
    name: "getIntent",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "intentId",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "payer",
            type: "address",
          },
          {
            internalType: "address",
            name: "token",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "string",
                name: "role",
                type: "string",
              },
              {
                internalType: "address",
                name: "wallet",
                type: "address",
              },
              {
                internalType: "uint16",
                name: "bps",
                type: "uint16",
              },
            ],
            internalType: "struct PaymentLib.Recipient[]",
            name: "recipients",
            type: "tuple[]",
          },
          {
            internalType: "enum PaymentLib.Status",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "createdAt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "context",
            type: "string",
          },
          {
            internalType: "address",
            name: "selectedExecutor",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "executorFee",
            type: "uint256",
          },
        ],
        internalType: "struct PaymentLib.PaymentIntent",
        name: "",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "string",
            name: "role",
            type: "string",
          },
          {
            internalType: "address",
            name: "wallet",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "bps",
            type: "uint16",
          },
        ],
        internalType: "struct PaymentLib.Recipient[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "intentId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "executor",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    name: "setSelectedExecutor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "intentId",
        type: "bytes32",
      },
      {
        internalType: "enum PaymentLib.Status",
        name: "status",
        type: "uint8",
      },
    ],
    name: "updateStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPaymentIntentRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IPaymentIntentRegistryInterface {
    return new Interface(_abi) as IPaymentIntentRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPaymentIntentRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPaymentIntentRegistry;
  }
}
