/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILLMAgent,
  ILLMAgentInterface,
} from "../../../../contracts/core/PlannerGateway.sol/ILLMAgent";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "systemPrompt",
        type: "string",
      },
      {
        internalType: "string",
        name: "userPrompt",
        type: "string",
      },
      {
        internalType: "string[]",
        name: "allowedValues",
        type: "string[]",
      },
    ],
    name: "inferString",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILLMAgent__factory {
  static readonly abi = _abi;
  static createInterface(): ILLMAgentInterface {
    return new Interface(_abi) as ILLMAgentInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ILLMAgent {
    return new Contract(address, _abi, runner) as unknown as ILLMAgent;
  }
}
