/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAgentRegistry__factory } from "./IAgentRegistry__factory";
export { PaymentReceiptRegistry__factory } from "./PaymentReceiptRegistry__factory";
