/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace VerifierGateway {
  export type ResponseStruct = { result: BytesLike; status: BigNumberish };

  export type ResponseStructOutput = [result: string, status: bigint] & {
    result: string;
    status: bigint;
  };

  export type RequestStruct = {
    agentId: BigNumberish;
    callbackAddress: AddressLike;
    callbackSelector: BytesLike;
    payload: BytesLike;
  };

  export type RequestStructOutput = [
    agentId: bigint,
    callbackAddress: string,
    callbackSelector: string,
    payload: string
  ] & {
    agentId: bigint;
    callbackAddress: string;
    callbackSelector: string;
    payload: string;
  };
}

export interface VerifierGatewayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LLM_AGENT_ID"
      | "agentPlatform"
      | "handleResponse"
      | "initSubscription"
      | "intentRegistry"
      | "onEvent"
      | "owner"
      | "receiptRegistry"
      | "renounceOwnership"
      | "settledStatusEmitter"
      | "supportsInterface"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PaymentVerified"
      | "VerificationFailed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LLM_AGENT_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentPlatform",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "handleResponse",
    values: [
      BigNumberish,
      VerifierGateway.ResponseStruct[],
      BigNumberish,
      VerifierGateway.RequestStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initSubscription",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "intentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onEvent",
    values: [AddressLike, BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receiptRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "settledStatusEmitter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "LLM_AGENT_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentPlatform",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "intentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onEvent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiptRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settledStatusEmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentVerifiedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    verificationHash: BytesLike,
    verifier: AddressLike
  ];
  export type OutputTuple = [
    intentId: string,
    verificationHash: string,
    verifier: string
  ];
  export interface OutputObject {
    intentId: string;
    verificationHash: string;
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationFailedEvent {
  export type InputTuple = [intentId: BytesLike, reason: string];
  export type OutputTuple = [intentId: string, reason: string];
  export interface OutputObject {
    intentId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VerifierGateway extends BaseContract {
  connect(runner?: ContractRunner | null): VerifierGateway;
  waitForDeployment(): Promise<this>;

  interface: VerifierGatewayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LLM_AGENT_ID: TypedContractMethod<[], [bigint], "view">;

  agentPlatform: TypedContractMethod<[], [string], "view">;

  handleResponse: TypedContractMethod<
    [
      requestId: BigNumberish,
      responses: VerifierGateway.ResponseStruct[],
      status: BigNumberish,
      arg3: VerifierGateway.RequestStruct
    ],
    [void],
    "nonpayable"
  >;

  initSubscription: TypedContractMethod<[], [void], "nonpayable">;

  intentRegistry: TypedContractMethod<[], [string], "view">;

  onEvent: TypedContractMethod<
    [emitter: AddressLike, eventTopics: BytesLike[], data: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  receiptRegistry: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  settledStatusEmitter: TypedContractMethod<[], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LLM_AGENT_ID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentPlatform"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "handleResponse"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      responses: VerifierGateway.ResponseStruct[],
      status: BigNumberish,
      arg3: VerifierGateway.RequestStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initSubscription"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "intentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onEvent"
  ): TypedContractMethod<
    [emitter: AddressLike, eventTopics: BytesLike[], data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receiptRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settledStatusEmitter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentVerified"
  ): TypedContractEvent<
    PaymentVerifiedEvent.InputTuple,
    PaymentVerifiedEvent.OutputTuple,
    PaymentVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationFailed"
  ): TypedContractEvent<
    VerificationFailedEvent.InputTuple,
    VerificationFailedEvent.OutputTuple,
    VerificationFailedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentVerified(bytes32,bytes32,address)": TypedContractEvent<
      PaymentVerifiedEvent.InputTuple,
      PaymentVerifiedEvent.OutputTuple,
      PaymentVerifiedEvent.OutputObject
    >;
    PaymentVerified: TypedContractEvent<
      PaymentVerifiedEvent.InputTuple,
      PaymentVerifiedEvent.OutputTuple,
      PaymentVerifiedEvent.OutputObject
    >;

    "VerificationFailed(bytes32,string)": TypedContractEvent<
      VerificationFailedEvent.InputTuple,
      VerificationFailedEvent.OutputTuple,
      VerificationFailedEvent.OutputObject
    >;
    VerificationFailed: TypedContractEvent<
      VerificationFailedEvent.InputTuple,
      VerificationFailedEvent.OutputTuple,
      VerificationFailedEvent.OutputObject
    >;
  };
}
