/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface SettlementEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentRegistry"
      | "executeSettlement"
      | "owner"
      | "paymentIntentRegistry"
      | "receiptRegistry"
      | "renounceOwnership"
      | "setReceiptRegistry"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ReceiptRegistrySet"
      | "SettlementExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeSettlement",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentIntentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiptRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setReceiptRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentIntentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiptRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReceiptRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiptRegistrySetEvent {
  export type InputTuple = [receiptRegistry: AddressLike];
  export type OutputTuple = [receiptRegistry: string];
  export interface OutputObject {
    receiptRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementExecutedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    executor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    executor: string,
    amount: bigint
  ];
  export interface OutputObject {
    intentId: string;
    executor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SettlementEngine extends BaseContract {
  connect(runner?: ContractRunner | null): SettlementEngine;
  waitForDeployment(): Promise<this>;

  interface: SettlementEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentRegistry: TypedContractMethod<[], [string], "view">;

  executeSettlement: TypedContractMethod<
    [intentId: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  paymentIntentRegistry: TypedContractMethod<[], [string], "view">;

  receiptRegistry: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setReceiptRegistry: TypedContractMethod<
    [_receiptRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executeSettlement"
  ): TypedContractMethod<[intentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentIntentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receiptRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReceiptRegistry"
  ): TypedContractMethod<[_receiptRegistry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReceiptRegistrySet"
  ): TypedContractEvent<
    ReceiptRegistrySetEvent.InputTuple,
    ReceiptRegistrySetEvent.OutputTuple,
    ReceiptRegistrySetEvent.OutputObject
  >;
  getEvent(
    key: "SettlementExecuted"
  ): TypedContractEvent<
    SettlementExecutedEvent.InputTuple,
    SettlementExecutedEvent.OutputTuple,
    SettlementExecutedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReceiptRegistrySet(address)": TypedContractEvent<
      ReceiptRegistrySetEvent.InputTuple,
      ReceiptRegistrySetEvent.OutputTuple,
      ReceiptRegistrySetEvent.OutputObject
    >;
    ReceiptRegistrySet: TypedContractEvent<
      ReceiptRegistrySetEvent.InputTuple,
      ReceiptRegistrySetEvent.OutputTuple,
      ReceiptRegistrySetEvent.OutputObject
    >;

    "SettlementExecuted(bytes32,address,uint256)": TypedContractEvent<
      SettlementExecutedEvent.InputTuple,
      SettlementExecutedEvent.OutputTuple,
      SettlementExecutedEvent.OutputObject
    >;
    SettlementExecuted: TypedContractEvent<
      SettlementExecutedEvent.InputTuple,
      SettlementExecutedEvent.OutputTuple,
      SettlementExecutedEvent.OutputObject
    >;
  };
}
