/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1363__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeERC20__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyGuard__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "ISomniaEventHandler",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISomniaEventHandler__factory>;
    getContractFactory(
      name: "ISomniaReactivityPrecompile",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISomniaReactivityPrecompile__factory>;
    getContractFactory(
      name: "SomniaExtensions",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SomniaExtensions__factory>;
    getContractFactory(
      name: "SomniaEventHandler",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SomniaEventHandler__factory>;
    getContractFactory(
      name: "AgentRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AgentRegistry__factory>;
    getContractFactory(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC20__factory>;
    getContractFactory(
      name: "IAgentRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAgentRegistry__factory>;
    getContractFactory(
      name: "IAgentRequester",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAgentRequester__factory>;
    getContractFactory(
      name: "IJsonApiAgent",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IJsonApiAgent__factory>;
    getContractFactory(
      name: "IPaymentIntentRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPaymentIntentRegistry__factory>;
    getContractFactory(
      name: "NegotiationGateway",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NegotiationGateway__factory>;
    getContractFactory(
      name: "PaymentIntentRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PaymentIntentRegistry__factory>;
    getContractFactory(
      name: "IAgentRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAgentRegistry__factory>;
    getContractFactory(
      name: "PaymentReceiptRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PaymentReceiptRegistry__factory>;
    getContractFactory(
      name: "IAgentRequester",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAgentRequester__factory>;
    getContractFactory(
      name: "ILLMAgent",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILLMAgent__factory>;
    getContractFactory(
      name: "IPaymentIntentRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPaymentIntentRegistry__factory>;
    getContractFactory(
      name: "PlannerGateway",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PlannerGateway__factory>;
    getContractFactory(
      name: "IAgentRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAgentRegistry__factory>;
    getContractFactory(
      name: "IPaymentIntentRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPaymentIntentRegistry__factory>;
    getContractFactory(
      name: "SettlementEngine",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SettlementEngine__factory>;
    getContractFactory(
      name: "IAgentPlatform",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAgentPlatform__factory>;
    getContractFactory(
      name: "ILLMAgent",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILLMAgent__factory>;
    getContractFactory(
      name: "VerifierGateway",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VerifierGateway__factory>;
    getContractFactory(
      name: "PaymentLib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PaymentLib__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1155Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "IERC1363",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1363>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "SafeERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeERC20>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "ReentrancyGuard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyGuard>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "ISomniaEventHandler",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISomniaEventHandler>;
    getContractAt(
      name: "ISomniaReactivityPrecompile",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISomniaReactivityPrecompile>;
    getContractAt(
      name: "SomniaExtensions",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SomniaExtensions>;
    getContractAt(
      name: "SomniaEventHandler",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SomniaEventHandler>;
    getContractAt(
      name: "AgentRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AgentRegistry>;
    getContractAt(
      name: "MockERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC20>;
    getContractAt(
      name: "IAgentRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAgentRegistry>;
    getContractAt(
      name: "IAgentRequester",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAgentRequester>;
    getContractAt(
      name: "IJsonApiAgent",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IJsonApiAgent>;
    getContractAt(
      name: "IPaymentIntentRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPaymentIntentRegistry>;
    getContractAt(
      name: "NegotiationGateway",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.NegotiationGateway>;
    getContractAt(
      name: "PaymentIntentRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PaymentIntentRegistry>;
    getContractAt(
      name: "IAgentRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAgentRegistry>;
    getContractAt(
      name: "PaymentReceiptRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PaymentReceiptRegistry>;
    getContractAt(
      name: "IAgentRequester",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAgentRequester>;
    getContractAt(
      name: "ILLMAgent",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILLMAgent>;
    getContractAt(
      name: "IPaymentIntentRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPaymentIntentRegistry>;
    getContractAt(
      name: "PlannerGateway",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PlannerGateway>;
    getContractAt(
      name: "IAgentRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAgentRegistry>;
    getContractAt(
      name: "IPaymentIntentRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPaymentIntentRegistry>;
    getContractAt(
      name: "SettlementEngine",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SettlementEngine>;
    getContractAt(
      name: "IAgentPlatform",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAgentPlatform>;
    getContractAt(
      name: "ILLMAgent",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILLMAgent>;
    getContractAt(
      name: "VerifierGateway",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VerifierGateway>;
    getContractAt(
      name: "PaymentLib",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PaymentLib>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "ISomniaEventHandler",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISomniaEventHandler>;
    deployContract(
      name: "ISomniaReactivityPrecompile",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISomniaReactivityPrecompile>;
    deployContract(
      name: "SomniaExtensions",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SomniaExtensions>;
    deployContract(
      name: "SomniaEventHandler",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SomniaEventHandler>;
    deployContract(
      name: "AgentRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentRegistry>;
    deployContract(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "IAgentRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentRegistry>;
    deployContract(
      name: "IAgentRequester",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentRequester>;
    deployContract(
      name: "IJsonApiAgent",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IJsonApiAgent>;
    deployContract(
      name: "IPaymentIntentRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPaymentIntentRegistry>;
    deployContract(
      name: "NegotiationGateway",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NegotiationGateway>;
    deployContract(
      name: "PaymentIntentRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PaymentIntentRegistry>;
    deployContract(
      name: "IAgentRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentRegistry>;
    deployContract(
      name: "PaymentReceiptRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PaymentReceiptRegistry>;
    deployContract(
      name: "IAgentRequester",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentRequester>;
    deployContract(
      name: "ILLMAgent",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILLMAgent>;
    deployContract(
      name: "IPaymentIntentRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPaymentIntentRegistry>;
    deployContract(
      name: "PlannerGateway",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PlannerGateway>;
    deployContract(
      name: "IAgentRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentRegistry>;
    deployContract(
      name: "IPaymentIntentRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPaymentIntentRegistry>;
    deployContract(
      name: "SettlementEngine",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SettlementEngine>;
    deployContract(
      name: "IAgentPlatform",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentPlatform>;
    deployContract(
      name: "ILLMAgent",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILLMAgent>;
    deployContract(
      name: "VerifierGateway",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VerifierGateway>;
    deployContract(
      name: "PaymentLib",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PaymentLib>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "IERC1363",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "ReentrancyGuard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "ISomniaEventHandler",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISomniaEventHandler>;
    deployContract(
      name: "ISomniaReactivityPrecompile",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISomniaReactivityPrecompile>;
    deployContract(
      name: "SomniaExtensions",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SomniaExtensions>;
    deployContract(
      name: "SomniaEventHandler",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SomniaEventHandler>;
    deployContract(
      name: "AgentRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentRegistry>;
    deployContract(
      name: "MockERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "IAgentRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentRegistry>;
    deployContract(
      name: "IAgentRequester",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentRequester>;
    deployContract(
      name: "IJsonApiAgent",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IJsonApiAgent>;
    deployContract(
      name: "IPaymentIntentRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPaymentIntentRegistry>;
    deployContract(
      name: "NegotiationGateway",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NegotiationGateway>;
    deployContract(
      name: "PaymentIntentRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PaymentIntentRegistry>;
    deployContract(
      name: "IAgentRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentRegistry>;
    deployContract(
      name: "PaymentReceiptRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PaymentReceiptRegistry>;
    deployContract(
      name: "IAgentRequester",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentRequester>;
    deployContract(
      name: "ILLMAgent",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILLMAgent>;
    deployContract(
      name: "IPaymentIntentRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPaymentIntentRegistry>;
    deployContract(
      name: "PlannerGateway",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PlannerGateway>;
    deployContract(
      name: "IAgentRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentRegistry>;
    deployContract(
      name: "IPaymentIntentRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPaymentIntentRegistry>;
    deployContract(
      name: "SettlementEngine",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SettlementEngine>;
    deployContract(
      name: "IAgentPlatform",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentPlatform>;
    deployContract(
      name: "ILLMAgent",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILLMAgent>;
    deployContract(
      name: "VerifierGateway",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VerifierGateway>;
    deployContract(
      name: "PaymentLib",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PaymentLib>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
