/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace PaymentReceiptRegistry {
  export type ReceiptStruct = {
    intentId: BytesLike;
    executor: AddressLike;
    verifier: AddressLike;
    txHash: BytesLike;
    amount: BigNumberish;
    recipientCount: BigNumberish;
    verified: boolean;
    timestamp: BigNumberish;
    receiptHash: BytesLike;
  };

  export type ReceiptStructOutput = [
    intentId: string,
    executor: string,
    verifier: string,
    txHash: string,
    amount: bigint,
    recipientCount: bigint,
    verified: boolean,
    timestamp: bigint,
    receiptHash: string
  ] & {
    intentId: string;
    executor: string;
    verifier: string;
    txHash: string;
    amount: bigint;
    recipientCount: bigint;
    verified: boolean;
    timestamp: bigint;
    receiptHash: string;
  };
}

export interface PaymentReceiptRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentRegistry"
      | "createReceipt"
      | "getReceipt"
      | "owner"
      | "receiptExistsFor"
      | "renounceOwnership"
      | "setSettlementEngine"
      | "settlementEngine"
      | "transferOwnership"
      | "verifyReceipt"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ReceiptCreated"
      | "ReceiptVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createReceipt",
    values: [BytesLike, AddressLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceipt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receiptExistsFor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSettlementEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settlementEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyReceipt",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getReceipt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiptExistsFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettlementEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlementEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyReceipt",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiptCreatedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    executor: AddressLike,
    receiptHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    executor: string,
    receiptHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    intentId: string;
    executor: string;
    receiptHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiptVerifiedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    verifier: AddressLike,
    receiptHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    verifier: string,
    receiptHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    intentId: string;
    verifier: string;
    receiptHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaymentReceiptRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PaymentReceiptRegistry;
  waitForDeployment(): Promise<this>;

  interface: PaymentReceiptRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentRegistry: TypedContractMethod<[], [string], "view">;

  createReceipt: TypedContractMethod<
    [
      intentId: BytesLike,
      executor: AddressLike,
      txHash: BytesLike,
      amount: BigNumberish,
      recipientCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getReceipt: TypedContractMethod<
    [intentId: BytesLike],
    [PaymentReceiptRegistry.ReceiptStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  receiptExistsFor: TypedContractMethod<
    [intentId: BytesLike],
    [boolean],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setSettlementEngine: TypedContractMethod<
    [_settlementEngine: AddressLike],
    [void],
    "nonpayable"
  >;

  settlementEngine: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyReceipt: TypedContractMethod<
    [intentId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createReceipt"
  ): TypedContractMethod<
    [
      intentId: BytesLike,
      executor: AddressLike,
      txHash: BytesLike,
      amount: BigNumberish,
      recipientCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getReceipt"
  ): TypedContractMethod<
    [intentId: BytesLike],
    [PaymentReceiptRegistry.ReceiptStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receiptExistsFor"
  ): TypedContractMethod<[intentId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSettlementEngine"
  ): TypedContractMethod<
    [_settlementEngine: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settlementEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyReceipt"
  ): TypedContractMethod<[intentId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReceiptCreated"
  ): TypedContractEvent<
    ReceiptCreatedEvent.InputTuple,
    ReceiptCreatedEvent.OutputTuple,
    ReceiptCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ReceiptVerified"
  ): TypedContractEvent<
    ReceiptVerifiedEvent.InputTuple,
    ReceiptVerifiedEvent.OutputTuple,
    ReceiptVerifiedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReceiptCreated(bytes32,address,bytes32,uint256)": TypedContractEvent<
      ReceiptCreatedEvent.InputTuple,
      ReceiptCreatedEvent.OutputTuple,
      ReceiptCreatedEvent.OutputObject
    >;
    ReceiptCreated: TypedContractEvent<
      ReceiptCreatedEvent.InputTuple,
      ReceiptCreatedEvent.OutputTuple,
      ReceiptCreatedEvent.OutputObject
    >;

    "ReceiptVerified(bytes32,address,bytes32,uint256)": TypedContractEvent<
      ReceiptVerifiedEvent.InputTuple,
      ReceiptVerifiedEvent.OutputTuple,
      ReceiptVerifiedEvent.OutputObject
    >;
    ReceiptVerified: TypedContractEvent<
      ReceiptVerifiedEvent.InputTuple,
      ReceiptVerifiedEvent.OutputTuple,
      ReceiptVerifiedEvent.OutputObject
    >;
  };
}
